require: rubocop-rails

Rails:
  Enabled: true

# slug とか created_by とか、NOT NULL だが create_table 時に
# default 値を定義できないカラムは存在する。
Rails/NotNullColumn:
  Enabled: false

# bin/ 以下の実行ファイルではトップレベルで include できて良い
Style/MixinUsage:
  Exclude:
    - 'bin/*'
