require: "rubocop-rspec"

# 短い subject は一行で書いて良い
RSpec/EmptyLineAfterSubject:
  Enabled: false

# it が一つしか無いような context では空行を開ける方が読みづらい
#   context "when foo is bar" do
#     let(:foo) { bar }
#     it { is_expected.to do_something }
#   end
RSpec/EmptyLineAfterFinalLet:
  Enabled: false

# 変に名前つけて呼ぶ方が分かりづらい。
# テスト対象メソッドを呼ぶだけの subject 以外を書かないようにする方が効く。
RSpec/NamedSubject:
  Enabled: false

# 強く 1 example 1 assertion の立場は取らないが、多すぎてもツラいので。
RSpec/MultipleExpectations:
  Max: 3


# Model
#  `- #method
#      |- 頻出ケースのテスト 1
#      |- 頻出ケースのテスト 2
#      `- レアケース
#          |- レアケースのテスト 1
#          `- レアケースのテスト 2
# のように括り出すと、レアケースのテストを読み飛ばせるようになり
# テストを読む人にやさしくなる。
# デフォルトの 3 より少し緩めてもヨサソウ。
RSpec/NestedGroups:
  Max: 4
